// Placeholder for ExperienciaService
import '../../models/experiencia/experiencia_model.dart';
import '../../models/experiencia/reserva_experiencia_model.dart';
import '../../models/reserva/reserva_model.dart' show EstadoReserva;


class ExperienciaService {
  Future<List<Experiencia>> getExperiencias({CategoriaExperiencia? categoria}) async {
    print('ExperienciaService (Placeholder): Fetching experiencias...');
    await Future.delayed(const Duration(seconds: 1));
    var experiencias = _getMockExperienciasFromService();
    if (categoria != null) {
        experiencias = experiencias.where((e) => e.categoria == categoria).toList();
    }
    return experiencias;
  }

  Future<Experiencia> getExperienciaDetails(String experienciaId) async {
    print('ExperienciaService (Placeholder): Fetching details for exp ID: $experienciaId');
    await Future.delayed(const Duration(seconds: 1));
    return _getMockExperienciasFromService().firstWhere((exp) => exp.id == experienciaId, orElse: () => _getMockExperienciasFromService().first);
  }

  Future<ReservaExperiencia> createReservaExperiencia({
    required String experienciaId,
    required String usuarioId,
    required DateTime fechaHoraExperiencia,
    required int numeroPersonas,
    required double costoTotalReserva,
    String? notasAdicionales,
  }) async {
    print('ExperienciaService (Placeholder): Creating reserva experiencia...');
    await Future.delayed(const Duration(seconds: 1));
    return ReservaExperiencia(
      id: 'srv_resexp_${DateTime.now().millisecondsSinceEpoch}',
      experienciaId: experienciaId,
      usuarioId: usuarioId,
      fechaHoraExperiencia: fechaHoraExperiencia,
      numeroPersonas: numeroPersonas,
      costoTotalReserva: costoTotalReserva,
      estado: EstadoReserva.confirmada,
      fechaCreacionReserva: DateTime.now(),
      notasAdicionales: notasAdicionales,
    );
  }

  Future<List<ReservaExperiencia>> getUserReservasExperiencia(String usuarioId) async {
    print('ExperienciaService (Placeholder): Fetching user reservas de experiencia for user $usuarioId');
    await Future.delayed(const Duration(seconds: 1));
    return [
        ReservaExperiencia(id: 'srv_resexp_u1', experienciaId: 'exp1', usuarioId: usuarioId, fechaHoraExperiencia: DateTime.now().add(const Duration(days: 10)), numeroPersonas: 1, costoTotalReserva: 80.0, estado: EstadoReserva.confirmada, fechaCreacionReserva: DateTime.now().subtract(const Duration(days:2))),
    ];
  }

  // Admin methods
  Future<Experiencia> createExperiencia(Experiencia data) async {
    print('ExperienciaService (Placeholder): Creating experiencia: ${data.nombre}');
    await Future.delayed(const Duration(seconds: 1));
    // In real service, ID would be generated by backend
    return data.copyWith(id: 'srv_exp_${DateTime.now().millisecondsSinceEpoch}');
  }

  Future<Experiencia> updateExperiencia(Experiencia data) async {
    print('ExperienciaService (Placeholder): Updating experiencia ID ${data.id}');
    await Future.delayed(const Duration(seconds: 1));
    return data; // Assume update is successful
  }

  Future<void> deleteExperiencia(String experienciaId) async {
    print('ExperienciaService (Placeholder): Deleting experiencia ID: $experienciaId');
    await Future.delayed(const Duration(seconds: 1));
  }

  List<Experiencia> _getMockExperienciasFromService() {
     return [
      Experiencia(id: 'exp1_srv', nombre: 'Tour en Kayak por Uros (Service)', descripcion: 'Explora las islas flotantes de los Uros en kayak desde el servicio.', lugarEncuentro: 'Muelle de Puno', duracionEstimadaHoras: 3, precioPorPersona: 85.0, anfitrionId: 'comunidad_uros_srv', categoria: CategoriaExperiencia.tourGuiado, capacidadMaximaPersonas: 10, incluye: ['Kayak', 'Guía'], fotos: [const FotoExperiencia(id:'fexp1_srv', url: 'https://via.placeholder.com/300x200.png?text=Kayak+Uros+Srv')]),
      Experiencia(id: 'exp2_srv', nombre: 'Taller de Textiles en Taquile (Service)', descripcion: 'Aprende técnicas ancestrales de tejido con artesanos locales desde el servicio.', lugarEncuentro: 'Plaza de Taquile', duracionEstimadaHoras: 4, precioPorPersona: 125.0, anfitrionId: 'cooperativa_taquile_srv', categoria: CategoriaExperiencia.tallerCultural, capacidadMaximaPersonas: 8, incluye: ['Materiales'], calificacionPromedio: 4.7, fotos: [const FotoExperiencia(id:'fexp2_srv', url: 'https://via.placeholder.com/300x200.png?text=Textiles+Taquile+Srv')]),
    ];
  }
}

// Helper extension for mock datacopyWith on Experiencia model
extension ExperienciaCopyWith on Experiencia {
  Experiencia copyWith({
    String? id,
    String? nombre,
    String? descripcion,
    String? lugarEncuentro,
    double? duracionEstimadaHoras,
    double? precioPorPersona,
    String? anfitrionId,
    List<FotoExperiencia>? fotos,
    CategoriaExperiencia? categoria,
    int? capacidadMaximaPersonas,
    List<String>? incluye,
    String? requisitos,
    double? calificacionPromedio,
  }) {
    return Experiencia(
      id: id ?? this.id,
      nombre: nombre ?? this.nombre,
      descripcion: descripcion ?? this.descripcion,
      lugarEncuentro: lugarEncuentro ?? this.lugarEncuentro,
      duracionEstimadaHoras: duracionEstimadaHoras ?? this.duracionEstimadaHoras,
      precioPorPersona: precioPorPersona ?? this.precioPorPersona,
      anfitrionId: anfitrionId ?? this.anfitrionId,
      fotos: fotos ?? this.fotos,
      categoria: categoria ?? this.categoria,
      capacidadMaximaPersonas: capacidadMaximaPersonas ?? this.capacidadMaximaPersonas,
      incluye: incluye ?? this.incluye,
      requisitos: requisitos ?? this.requisitos,
      calificacionPromedio: calificacionPromedio ?? this.calificacionPromedio,
    );
  }
}
